/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/h5`
 */
// #region Interfaces
export interface SpmH5SDKCKOptions {
  target: HTMLElement;
  spm: string;
  scm: string;
  biz_type: string;
  event_id?: string;
  json_param?: string;
}
export interface SpmH5SDKEPOptions {
  target: HTMLElement;
  spm: string;
  scm: string;
  biz_type: string;
  event_id?: string;
  json_param?: string;
}
export interface SpmH5SDKInstallOptions {
  siteId: string;
  account?: string;
  ma_app_id?: string;
  autoClickTag?: string;
  autoExpTag?: string;
  [key: string]: string | boolean | undefined;
}
export interface SpmH5SDKPVOptions {
  spm: string;
  page_id?: string;
  page_param?: string;
  trafficmap_aid?: string;
}
// #endregion

// #region Classes
export declare class SpmH5SDK {
  static install(_: SpmH5SDKInstallOptions): void;
  static pv(_: SpmH5SDKPVOptions): void;
  static ck(_: SpmH5SDKCKOptions): void;
  static ep(_: SpmH5SDKEPOptions): void;
}
// #endregion