/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk`
 */
// #region Classes
export declare class SpmH5SDK {
  static install(_: SpmH5SDKInstallOptions): void;
  static pv(_: SpmH5SDKPVOptions): void;
  static ck(_: SpmH5SDKCKOptions): void;
  static ep(_: SpmH5SDKEPOptions): void;
}
export declare class SpmJDMPSDK {
  static pv(_: SpmJDMPSDKPVOptions): void;
  static ck(_: SpmJDMPSDKCKOptions): void;
  static ep(_: SpmJDMPSDKEPOptions): void;
}
export declare class SpmJDRNSDK {}
export declare class SpmPCSDK {
  static install(_: SpmPCSDKInstallOptions): void;
  static pv(_: SpmPCSDKPVOptions): void;
  static ck(_: SpmPCSDKCKOptions): void;
  static ep(_: SpmPCSDKEPOptions): void;
  static sys(): void;
}
export declare class SpmTNSDK {}
export declare class SpmWXMPSDK {
  private static log;
  static install(_: SpmWXMPSDKInstallOptions): void;
  static pv(_: SpmWXMPSDKPVOptions): void;
  static ck(_: SpmWXMPSDKCKOptions): void;
  static ep(_: SpmWXMPSDKEPOptions): void;
}
// #endregion