/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/jdmp`
 */
// #region Interfaces
export interface SpmJDMPSDKCKOptions {
  spm: string;
  biz_type?: string;
  eventId: string;
  pageId?: string;
  pageParam?: string;
  eventParam?: string;
  jsonParam?: string;
  scm?: string;
}
export interface SpmJDMPSDKEPOptions {
  spm: string;
  biz_type?: string;
  eid: string;
  pageId?: string;
  jsonParam?: string;
  map?: string;
  scm?: string;
}
export interface SpmJDMPSDKPVOptions {
  spm: string;
  biz_type?: string;
  pageId: string;
  pageName: string;
  pageParam?: string;
}
// #endregion

// #region Classes
export declare class SpmJDMPSDK {
  static pv(_: SpmJDMPSDKPVOptions): void;
  static ck(_: SpmJDMPSDKCKOptions): void;
  static ep(_: SpmJDMPSDKEPOptions): void;
}
// #endregion