/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/jdrn`
 */
// #region Interfaces
export interface SpmJDRNSDKCKOptions {
  spm: string;
  biz_type?: string;
  event_id?: string;
  event_param?: string;
  event_func?: string;
  page?: string;
  page_param?: string;
  next_page_param?: string;
  page_id?: string;
  shop_id?: string;
  json_param?: string;
  order_id?: string;
  sku?: string;
  sku_tag?: string;
  webDelayTime?: number;
  ext?: Record<string, unknown>;
}
export interface SpmJDRNSDKEPOptions {
  spm: string;
  biz_type?: string;
  page?: string;
  page_id?: string;
  page_param?: string;
  event_id?: string;
  event_param?: string;
  shop_id?: string;
  order_id?: string;
  sku_tag?: string;
  event_func?: string;
  next_page_param?: string;
  json_param?: string;
  level?: string;
  webDelayTime?: number;
  ext?: Record<string, unknown>;
}
export interface SpmJDRNSDKPVOptions {
  spm: string;
  biz_type?: string;
  page?: string;
  page_param?: string;
  page_id?: string;
  shop_id?: string;
  ext?: Record<string, unknown>;
}
// #endregion

// #region Classes
export declare class SpmJDRNSDK {
  static install(): void;
  static pv(_: SpmJDRNSDKPVOptions): void;
  static ck(_: SpmJDRNSDKCKOptions): void;
  static ep(_: SpmJDRNSDKEPOptions): void;
}
// #endregion