/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/jdrn`
 */
// #region Classes
export declare class SpmJDRNSDK {
  static install(): void;
  static pv(): void;
  static ck(): void;
  static ep(): void;
}
// #endregion