/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/pc`
 */
// #region Interfaces
export interface SpmPCSDKCKOptions {
  spm: string;
  biz_type?: string;
  page_id?: string;
  event_param?: string;
  json_param?: string;
}
export interface SpmPCSDKEPOptions {
  spm: string;
  biz_type?: string;
  page_id?: string;
  event_param?: string;
  json_param?: string;
  customAccount?: string;
}
export interface SpmPCSDKInstallOptions {
  account: string;
  domain?: string;
  maAppId?: string;
  auto_fullclick?: boolean;
  [key: string]: string | boolean | undefined;
}
export interface SpmPCSDKPVOptions {
  spm: string;
  page_id?: string;
  page_param?: string;
}
// #endregion

// #region Classes
export declare class SpmPCSDK {
  static install(_: SpmPCSDKInstallOptions): void;
  static pv(_: SpmPCSDKPVOptions): void;
  static ck(_: SpmPCSDKCKOptions): void;
  static ep(_: SpmPCSDKEPOptions): void;
  static sys(): void;
}
// #endregion