/**
 * Generated by tsnapi — public API snapshot of `@jd/spm-sdk/wxmp`
 */
// #region Interfaces
export interface SpmWXMPSDKCKOptions {
  spm: string;
  biz_type: string;
  event_id?: string;
  page_id?: string;
  eparam?: string;
  pparam?: string;
}
export interface SpmWXMPSDKEPOptions {
  spm: string;
  biz_type: string;
  event_id?: string;
  page_id?: string;
  eparam?: string;
  pparam?: string;
}
export interface SpmWXMPSDKInstallOptions {
  siteId: string;
  appid: string;
  account: string;
  openid: string;
  unionid: string;
  latitude?: string;
  longitude?: string;
  [key: string]: string | boolean | undefined;
}
export interface SpmWXMPSDKPVOptions {
  spm: string;
  page_id?: string;
  pparam?: string;
}
// #endregion

// #region Classes
export declare class SpmWXMPSDK {
  private static log;
  static install(_: SpmWXMPSDKInstallOptions): void;
  static pv(_: SpmWXMPSDKPVOptions): void;
  static ck(_: SpmWXMPSDKCKOptions): void;
  static ep(_: SpmWXMPSDKEPOptions): void;
}
// #endregion