name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: bjmhe/workflows/.github/workflows/release.yml@vp
    with:
      publish: false
    permissions:
      contents: write
      id-token: write
